accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html'),
            name='login'
    ),
    path('logout/',
    auth_views.LogoutView.as_view(),
    name='logout'
    ),
    path('signup/', views.signup, name='signup'),
    path('signup/custom/', views.signup_custom, name='signup_custom'),
    path('logout/',views.logout , name='logout')


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from firstapp import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index),
    path("mbti/", include('secondapp.urls')),
    path("accounts/", include('accounts.urls')),
    path("", include('file.urls')),
    path("board/", include('board.urls')),
    path("secondapp/", include('secondapp.urls')),
    path("", include('mbtiapp.urls')),
    path("", views.main),

    
   
    
]

file/urls.py
from django.urls import path
from file import views


urlpatterns = [
    path('insert/',views.insert),
    path('mbti/<str:kind>/',views.show),
    path('index/',views.index),
]

accounts/models.py
from django.db import models

class Member(models.Model):
    user_id = models.CharField(max_length=50, unique=True)
    user_pw = models.CharField(max_length=50)
    user_name = models.CharField(max_length=50)
    date_joined = models.DateTimeField()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "email")

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/index')
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form': form})

from .models import Member
from django.utils import timezone
from django.http import HttpResponse
def signup_custom(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user_pw = request.POST.get('user_pw')
        user_name = request.POST.get('user_name')
        m = Member(
            user_id=user_id, user_pw=user_pw, user_name=user_name)
        m.date_joined = timezone.now()
        m.save()
        return HttpResponse(
            '가입 완료<br>%s %s %s' % (user_id, user_pw, user_name))
    else:
        return render(request, 'accounts/signup_custom.html')
    
def logout(request):
    if request.method == 'POST':
        redirect('index/')
    return render(request, 'mbti/index.html')

accounts/templates/accounts/login.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        {% include "mbti/form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value | default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value | default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    
</div>

accounts/templates/accounts/signup.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'accounts:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "mbti/form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value | default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value | default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value | default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value | default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>

accounts/templates/accounts/signup_custom.html
<form method="post">
    {% csrf_token %}
    아이디 : <input type="text" name="user_id"><br>
    비밀번호 : <input type="text" name="user_pw"><br>
    이름 : <input type="text" name="user_name"><br>
    <input type="submit" value="가입">
</form>